apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  name: {{ .Values.cosmosdb.name  }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  instanceRef:
    name: {{ .Values.cosmosdb.name  }}
  secretName: {{ .Values.cosmosdb.name  }}
  secretTransforms:
    -
      renameKey:
        from: connectionString
        to: MONGODB_URI
